RedditApp/config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user GET    /users/:id(.:format)                                                                     users#show
#                      subs GET    /subs(.:format)                                                                          subs#index
#                           POST   /subs(.:format)                                                                          subs#create
#                   new_sub GET    /subs/new(.:format)                                                                      subs#new
#                  edit_sub GET    /subs/:id/edit(.:format)                                                                 subs#edit
#                       sub GET    /subs/:id(.:format)                                                                      subs#show
#                           PATCH  /subs/:id(.:format)                                                                      subs#update
#                           PUT    /subs/:id(.:format)                                                                      subs#update
#               new_session GET    /session/new(.:format)                                                                   sessions#new
#                   session DELETE /session(.:format)                                                                       sessions#destroy
#                           POST   /session(.:format)                                                                       sessions#create
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index]

  resources :subs, only: [:show, :index, :new, :edit, :create, :update]

  resource :session, only: [:new, :create, :destroy]
end

RedditApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditApp/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  desciption :text             not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Sub < ApplicationRecord

    validates :title, :desciption, presence: true
    
    belongs_to :user

end

RedditApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :username, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: {minimum: 6}, allow_nil: true

    after_initialize :ensure_session_token
    attr_reader :password

    has_many :subs

    def self.find_by_credentials(username,password)
        user = User.find_by(username: username)
        return nil unless user && user.is_password?(password)
        user
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end 

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = self.class.generate_session_token
        self.save!
        self.session_token
    end 

    private
    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end 
    
    def ensure_session_token
        self.session_token ||= self.class.generate_session_token
    end 
end

RedditApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    # private

    def current_user
        # debugger
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def ensure_logged_in
        # debugger
        redirect_to new_session_url unless logged_in?
    end

    def login(user)
        @current_user = user
        session[:session_token] = user.reset_session_token!
    end

    def logout
        current_user.reset_session_token!
        session[:session_token] = nil 
    end

    def logged_in?
        !!current_user
    end

end

RedditApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :ensure_logged_in, only: [:destroy]

    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password])

        if @user
            login(@user)
            redirect_to subs_url
        else
            flash.now[:errors] = ['Invalid Credentials']
            render :new
        end
    end

    def destroy
        logout
        redirect_to new_session_url
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

RedditApp/app/controllers/subs_controller.rb
class SubsController < ApplicationController

    before_action :ensure_logged_in

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = Sub.new(sub_params)
        @sub.user_id = current_user.id

        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end

    end

    def show
        @sub = Sub.find(params[:id])
        render :show
    end

    def index
        @subs = Sub.all
        render :index 
    end

    def edit
        @sub = Sub.find(params[:id])
        render :edit
    end

    def update
        @sub = Sub.find(params[:id])
        
        if (@sub.user_id == current_user.id) && @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    private

    def sub_params
        params.require(:sub).permit(:title, :desciption)
    end

end

RedditApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :ensure_logged_in, only: [:index, :show]

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        
        if @user.save
            login(@user)
            redirect_to subs_url
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def index
        @users = User.all
        render :index
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

RedditApp/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditApp/app/helpers/subs_helper.rb
module SubsHelper
end

RedditApp/app/helpers/users_helper.rb
module UsersHelper
end

RedditApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <form action=<%=session_url%> method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <button>Log out</button>
      </form>
      <% else %>
      <a href="<%= new_session_url %>">Sign In</a>
      <br>
      <a href="<%= new_user_url %>">Sign Up</a>
    <% end%>
    <% if flash[:errors] %>
      <%= flash[:errors].join(", ") %>
    <% end%>
    <%= yield %>
  </body>
</html>

RedditApp/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label >Title
        <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>
    <br>
    <label >Description
        <input type="textarea" name="sub[desciption]" value="<%= @sub.desciption %>">
    </label>

    <button>Update Sub</button>

</form>

RedditApp/app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
    <% @subs.each do |sub| %>
        <li>
            <a href="<%= sub_url(sub) %>" ><%= sub.title %></a>
        </li>
    <% end %>
</ul>
<br>
<a href="<%= new_sub_url %>">Create a Sub</a>

RedditApp/app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action="<%= subs_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label >Title
        <input type="text" name="sub[title]">
    </label>
    <br>
    <label >Description
        <input type="textarea" name="sub[desciption]">
    </label>

    <button>Create Sub</button>

</form>

RedditApp/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<br>
<p>
    <%= @sub.desciption %>
</p>
<br>
<% if @sub.user_id == current_user.id %>
    <a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>
<% end %>
<br>
<a href="<%= subs_url %>">Back to index</a>

RedditApp/app/views/users/index.html.erb
<h1>Users Index</h1>

RedditApp/app/views/users/new.html.erb
<h1>Sign up</h1>

<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    
    <label>Username
        <input type="text" name="user[username]" >
    </label>
    
    <label>Password
        <input type="password" name="user[password]" >
    </label>

    <button>Sign Up</button>

</form>

RedditApp/app/views/users/show.html.erb
<h1>Users Show</h1>